using Write;
using Write.Test;

Document build_rich() {
    var d = Document.create_blank();
    d.meta.title = "Rich";
    d.meta.custom["Project"] = "Apollo";
    d.body.clear();
    var title = new Paragraph.with_text("Main Title", "Title");
    d.body.add(title);
    var toc = new FieldBlock("TOC \\o \"1-3\" \\h \\z \\u");
    toc.result.add(new Paragraph.with_text("Chapter One\t1", "TOC1"));
    d.body.add(toc);
    var h = new Paragraph.with_text("Chapter One", "Heading1");
    h.inlines.insert(0, new Mark(MarkKind.BOOKMARK_START, "_Toc1"));
    h.inlines.add(new Mark(MarkKind.BOOKMARK_END, "_Toc1"));
    d.body.add(h);
    var p = new Paragraph();
    var cp = new CharProps();
    cp.font = "Liberation Sans";
    cp.size = 14;
    cp.color = "#aa0000";
    cp.highlight = "#ffff00";
    cp.caps = Caps.SMALL;
    cp.underline = Underline.DOUBLE;
    p.inlines.add(new TextRun("Styled ", cp));
    var cid = "5";
    p.inlines.add(new Mark(MarkKind.COMMENT_START, cid));
    p.inlines.add(new TextRun("commented"));
    p.inlines.add(new Mark(MarkKind.COMMENT_END, cid));
    var ins = new TextRun(" inserted");
    ins.rev = new Revision(RevKind.INSERT, "Grace", "2026-09-01T10:00:00Z");
    p.inlines.add(ins);
    var del = new TextRun(" removed");
    del.rev = new Revision(RevKind.DELETE, "Grace", "2026-09-01T10:00:00Z");
    p.inlines.add(del);
    p.inlines.add(new Tab());
    p.inlines.add(new FieldRun("PAGE", "1"));
    p.inlines.add(new FieldRun("DATE \\@ \"d MMMM yyyy\"", "1 September 2026"));
    p.inlines.add(new FieldRun("CITATION Knu84", "(Knuth, 1984)"));
    var note = new Note(NoteKind.ENDNOTE);
    note.blocks.add(new Paragraph.with_text("An endnote."));
    p.inlines.add(new NoteRef(note));
    p.props.align = Align.JUSTIFY;
    p.props.ind_left = 36;
    p.props.ind_first = -18;
    p.props.space_before = 6;
    p.props.space_after = 12;
    p.props.line = 1.5;
    p.props.keep_next = Tri.ON;
    p.props.border_bottom = new Border.with("single", 1, "#123456");
    p.props.shading = "#eeeeee";
    p.props.tabs = new Gee.ArrayList<TabStop>();
    p.props.tabs.add(new TabStop(300, TabAlign.RIGHT, TabLeader.DOT));
    d.body.add(p);
    var com = new Comment(cid, "Grace Hopper");
    com.blocks.add(new Paragraph.with_text("Check this."));
    d.comments.add(com);
    var reply = new Comment("6", "Ada");
    reply.parent_id = cid;
    reply.done = true;
    reply.blocks.add(new Paragraph.with_text("Done."));
    d.comments.add(reply);
    var cstyle = new Style("MyStyle", "My Style");
    cstyle.based_on = "Normal";
    cstyle.custom = true;
    cstyle.quick = true;
    cstyle.chr.bold = Tri.ON;
    cstyle.para.space_after = 20;
    d.styles.add(cstyle);
    var ps = new Paragraph.with_text("Custom styled", "MyStyle");
    ps.section = new Section();
    ps.section.columns = 2;
    ps.section.column_space = 24;
    ps.section.start = SectionStart.CONTINUOUS;
    d.body.add(ps);
    var t = Table.create(2, 3, 450);
    t.rows[0].header = true;
    t.rows[0].cells[0].span = 2;
    t.rows[0].cells.remove_at(1);
    t.rows[0].cells[0].shading = "#ddeeff";
    ((Paragraph) t.rows[1].cells[2].blocks[0]).inlines.add(new TextRun("cell"));
    t.rows[1].cells[0].vmerge = VMerge.RESTART;
    d.body.add(t);
    var sp = new Paragraph();
    var box = new ShapeRun(ShapeKind.TEXT_BOX);
    box.wrap = Wrap.SQUARE;
    box.width = 120;
    box.height = 60;
    box.hoff = 30;
    box.text.add(new Paragraph.with_text("In a box"));
    sp.inlines.add(box);
    var chk = new FormField(FormKind.CHECKBOX);
    chk.name = "Agree";
    chk.checked = true;
    sp.inlines.add(chk);
    sp.inlines.add(new Break(BreakKind.PAGE));
    sp.inlines.add(new Mark(MarkKind.INDEX_ENTRY, "Apollo"));
    d.body.add(sp);
    var src = new BibSource();
    src.tag = "Knu84";
    src.authors = { "Knuth, Donald E." };
    src.title = "The TeXbook";
    src.year = "1984";
    src.publisher = "Addison-Wesley";
    d.sources.add(src);
    var hdr = new HeaderFooter();
    var hp = new Paragraph.with_text("Header text ", "Header");
    hp.inlines.add(new FieldRun("PAGE", "1"));
    hdr.blocks.add(hp);
    d.final_section.header_default = hdr;
    var first_ftr = new HeaderFooter();
    first_ftr.blocks.add(new Paragraph.with_text("First footer", "Footer"));
    d.final_section.footer_first = first_ftr;
    d.final_section.title_page = true;
    d.final_section.set_orientation(true);
    d.final_section.page_start = 5;
    d.final_section.page_format = NumFormat.UPPER_ROMAN;
    d.track_changes = true;
    d.protection.kind = ProtectKind.COMMENTS;
    d.watermark = null;
    d.page_color = "#fdf6e3";
    var bl = d.numbering.make_bullets();
    int nid = d.numbering.add_instance(bl);
    var li = new Paragraph.with_text("Listed", "ListParagraph");
    li.props.num_id = nid;
    li.props.num_level = 0;
    d.body.add(li);
    return d;
}

void check_rich(Document d, string label, bool odt = false) {
    check(find_para(d, "Main Title") != null && find_para(d, "Main Title").style == "Title", label + ": title style");
    FieldBlock? toc = null;
    foreach (var b in d.body.items) if (b is FieldBlock) toc = (FieldBlock) b;
    check(toc != null && toc.kind() == "TOC", label + ": TOC field block");
    if (toc != null) check(toc.result.size >= 1 && ((Paragraph) toc.result[0]).plain_text().contains("Chapter One"), label + ": TOC result kept");
    var h = find_para(d, "Chapter One");
    bool bm = false;
    foreach (var p in d.paragraphs(false)) foreach (var i in p.inlines) if (i is Mark && ((Mark) i).kind == MarkKind.BOOKMARK_START && ((Mark) i).name == "_Toc1") bm = true;
    check(h != null && bm, label + ": bookmark");
    var styled = find_run(d, "Styled");
    check(styled != null, label + ": styled run");
    if (styled != null) {
        var c = styled.props;
        check(c.font == "Liberation Sans" && c.size == 14 && c.color == "#aa0000" && c.highlight == "#ffff00" && c.caps == Caps.SMALL && c.underline == Underline.DOUBLE, label + ": char props");
    }
    var p = find_para(d, "commented");
    check(p != null, label + ": comment paragraph");
    if (p != null) {
        var pp = p.props;
        check(pp.align == Align.JUSTIFY && pp.ind_left == 36 && pp.ind_first == -18 && pp.space_before == 6 && pp.space_after == 12, label + ": para props");
        check_near(pp.line, 1.5, 0.001, label + ": line spacing");
        check(pp.keep_next == Tri.ON && pp.border_bottom != null && pp.border_bottom.color == "#123456" && pp.shading == "#eeeeee", label + ": para borders shading keep");
        check(pp.tabs != null && pp.tabs.size == 1 && pp.tabs[0].align == TabAlign.RIGHT && pp.tabs[0].leader == TabLeader.DOT, label + ": tab stops");
        bool cs = false, ce = false, ins = false, del = false, page = false, date = false, cite = false, endnote = false;
        foreach (var i in p.inlines) {
            var m = i as Mark;
            if (m != null && m.kind == MarkKind.COMMENT_START) cs = true;
            if (m != null && m.kind == MarkKind.COMMENT_END) ce = true;
            if (i.rev != null && i.rev.kind == RevKind.INSERT && i.rev.author == "Grace") ins = true;
            if (i.rev != null && i.rev.kind == RevKind.DELETE && ((TextRun) i).text == " removed") del = true;
            var f = i as FieldRun;
            if (f != null && f.kind() == "PAGE") page = true;
            if (f != null && f.kind() == "DATE" && f.code.contains("MMMM")) date = true;
            if (f != null && f.kind() == "CITATION") cite = true;
            var n = i as NoteRef;
            if (n != null && n.note.kind == NoteKind.ENDNOTE && n.note.blocks.first_paragraph().plain_text().contains("An endnote.")) endnote = true;
        }
        check(cs && ce, label + ": comment range");
        check(ins && del, label + ": tracked insert and delete");
        check(page && date && cite, label + ": fields");
        check(endnote, label + ": endnote");
    }
    check(d.comments.size == 2 && d.comments[0].author == "Grace Hopper" && d.comments[0].text() == "Check this.", label + ": comment content");
    if (d.comments.size == 2) check(d.comments[1].parent_id == d.comments[0].id && d.comments[1].done, label + ": comment reply and resolved");
    var st = d.styles.get("MyStyle");
    check(st != null && st.custom && st.based_on == "Normal" && st.chr.bold == Tri.ON && st.para.space_after == 20, label + ": custom style");
    var cs_para = find_para(d, "Custom styled");
    check(cs_para != null && cs_para.section != null && cs_para.section.columns == 2 && (odt || cs_para.section.start == SectionStart.CONTINUOUS), label + ": section with columns");
    Table? t = null;
    foreach (var b in d.body.items) if (b is Table) t = (Table) b;
    check(t != null && t.rows.size == 2 && t.rows[0].header && t.rows[0].cells[0].span == 2 && t.rows[0].cells[0].shading == "#ddeeff", label + ": table header span shading");
    if (t != null) check((odt || t.rows[1].cells[0].vmerge == VMerge.RESTART) && t.rows[1].cells[2].plain_text() == "cell", label + ": table merge and text");
    ShapeRun? box = first_of<ShapeRun>(d);
    check(box != null && box.kind == ShapeKind.TEXT_BOX && box.wrap == Wrap.SQUARE && box.text.first_paragraph().plain_text() == "In a box", label + ": text box");
    if (box != null) check_near(box.hoff, 30, 0.1, label + ": text box offset");
    FormField? chk = first_of<FormField>(d);
    if (!odt) check(chk != null && chk.kind == FormKind.CHECKBOX && chk.checked && chk.name == "Agree", label + ": checkbox form field");
    Break? br = first_of<Break>(d);
    bool pb = br != null && br.kind == BreakKind.PAGE;
    if (odt) foreach (var bp in d.paragraphs(false)) if (bp.props.page_break_before == Tri.ON) pb = true;
    check(pb, label + ": page break");
    bool xe = false;
    foreach (var pp2 in d.paragraphs(false)) foreach (var i in pp2.inlines) if (i is Mark && ((Mark) i).kind == MarkKind.INDEX_ENTRY && ((Mark) i).name == "Apollo") xe = true;
    check(xe, label + ": index entry");
    check(d.sources.size == 1 && d.sources[0].tag == "Knu84" && d.sources[0].authors[0] == "Knuth, Donald E." && d.sources[0].year == "1984", label + ": bibliography source");
    var s = d.final_section;
    check(s.header_default != null && s.header_default.blocks.first_paragraph().plain_text().has_prefix("Header text"), label + ": header");
    check(s.footer_first != null && s.title_page, label + ": first page footer");
    check(s.landscape && s.page_w > s.page_h, label + ": landscape");
    check((odt || s.page_start == 5) && s.page_format == NumFormat.UPPER_ROMAN, label + ": page numbering");
    check(d.track_changes && (odt || d.protection.kind == ProtectKind.COMMENTS), label + ": settings");
    check(d.page_color == "#fdf6e3", label + ": page color");
    check(d.meta.title == "Rich" && d.meta.custom["Project"] == "Apollo", label + ": properties");
    var li = find_para(d, "Listed");
    check(li != null && li.props.num_id > 0 && d.numbering.def_for(li.props.num_id).is_bullet(), label + ": list");
}

